version: "3.5"

services:
  ocsen-nodejs:
    image: "ocsen-nodejs:latest"
    restart: on-failure
    container_name: ocsen-nodejs-release
    ports:
      - 8888:8888
    networks:
      - ocsen_network

networks:
  ocsen_network:
    driver: bridge
